### PR TITLE
update documentation - add information about versions of docker tools

### LINKED ISSUE #2: Docker requirements
Can you provide some guidance in the readme about the requirements for versions of docker or other dependencies?  I tried to spin this up on Ubuntu 16.04 (actually Ubuntu 16.04 in Windows 10 WSL) but got errors related to the version of docker-compose I installed with apt-get install.  Are there recommendations for how I should obtain a compliant docker on a stock Ubuntu 16.04 machine?

### PR DESCRIPTION
**Pull request by opadron**
fixes #2

### CODE REVIEW

**Comment by aashish24** [comment]
this looks reasonable. Perhaps add links to the download / install page for docker and docker-compose?

**Comment by aashish24** [comment]
@opadron do you think its reasonable to put links to docker and docker-compose in the docs? and then we can close this issue?

**Comment by opadron** [comment]
Updated.  PTAL.

**Comment by aashish24** [comment]
@opadron the changes looks good to me. Do we need anything else? if not I think we can merge this?

**Pull request merged**
