### PR TITLE
Show job progress in GirderJobList

### PR DESCRIPTION
**Pull request by jbeezley**
This adds a mechanism for receiving server side notifications (`sse.js`) which is attached to the session object.  It uses the `EventSource` by default and falls back to polling the notification endpoint (required https://github.com/girder/girder/pull/2769).

The `GirderJobList` component listens to job status changes and refetches from server.  This could be made smarter by updating the job models in place, but that can be left for a future enhancement.

### CODE REVIEW

**Comment by zachmullen** [comment]
Once this is ready, we should port the notification related stuff into girder_web_components.

**Comment by aashish24** [comment]
that sounds good I guess if Jon is okay with it. I am assuming that by mean ready, when merges into master? On this note, do we have a sense of timeline when we can start using girder_vue?

**Comment by zachmullen** [comment]
> I am assuming that by mean ready, when merges into master?

Sure, when you guys are happy with it for resonantgeo.

> do we have a sense of timeline when we can start using girder_vue

The repository is here: https://github.com/girder/girder_web_components/

We're trying to get all the infrastructure established -- the first component is ready (an Upload widget), but it still needs a way to demonstrate its capabilities either as part of a test or, better, an example. I'm hoping next week I'll have such an example, then we can start to think about things like a release process to npm.

**Pull request merged**
